Models/Enquiry.cs
namespace turbolinks_example
{
  public class Enquiry
  {
    public string Email { get; set; }
    public string Subject { get; set; }
    public string Message { get; set; }
  }
}

Controllers/EnquiryController.cs
using Microsoft.AspNetCore.Mvc;

namespace turbolinks_example
{
  public class EnquiryController : Controller
  {
    public IActionResult Index() => View();

    [HttpPost]
    public IActionResult Receive(Enquiry enquiry) => RedirectToAction(nameof(Received), enquiry);

    public IActionResult Received(Enquiry enquiry) => View(enquiry);

  }

}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace turbolinks_example
{
  public class HomeController : Controller
  {
    public IActionResult Index() => View();

    public IActionResult About() => View();

  }

}

Views/Enquiry/Index.cshtml
<h1>Enquiry</h1>

<form method="post" asp-controller="Enquiry" asp-action="Receive">

  <input name="Email" type="email" placeholder="email" value="joe@domain.com" required>
  <input name="Subject" placeholder="subject" required>
  <textarea name="Message" rows="5" placeholder="message" required></textarea>

  <button>Send</button>

</form>

Views/Enquiry/Received.cshtml
@model Enquiry

<h1>Received</h1>
<div>
  @Model.Email
</div>
<div>
  @Model.Subject
</div>
<div>
  @Model.Message
</div>

Views/Home/About.cshtml
<h1>About</h1>

Views/Home/Index.cshtml
<h1>Home</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="~/css/milligram.min.css">
  <script src="~/js/lib/turbolinks.js"></script>
  <script>
      (() => {
        const application = Stimulus.Application.start()
  
        application.register("hello", class extends Stimulus.Controller {
          static get targets() {
            return [ "name" ]
          }
  
          // …
        })
      })()
    </script>
  <script>

    function sendForm(form) {
      
      try {
        
        let data = new FormData();
  
        [...form.elements].forEach((x) => data.append(x.name, x.value));
  
        fetch(form.action, {
          method: form.method,
          body: data
        }).then((resp) => {
        
            window.Turbolinks.clearCache();
            
            const url = 'http://localhost:5000/Enquiry/Received';

            window.Turbolinks.visit(url);
        
        });
        
      } catch (error) {
        console.error('Error:', error);
      }

    }

    document.addEventListener('DOMContentLoaded', () => {
      
      document.addEventListener("turbolinks:load", () => {
        document.querySelectorAll('form').forEach((el) => {
          el.onsubmit = (e) => {
            e.preventDefault();
            sendForm(e.target);
          }

        });
      });
      
    });

  </script>
</head>

<body>

  <nav>

    <a asp-controller="Home" asp-action="Index">Home</a>

    <a asp-controller="Home" asp-action="About">About</a>

    <a asp-controller="Enquiry" asp-action="Index">Enquiry</a>

  </nav>

  @RenderBody()

</body>

</html>